name: Release

on:
  push:
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: "nixpkgs=channel:release-23.11"
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: |
          bash .github/scripts/build-slide.sh
          tar czf slide.tar.gz slide
      - uses: actions/upload-artifact@v4
        with:
          name: slide-archive
          path: slide.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/download-artifact@v4
        with:
          name: slide-archive
      - run: |
          tar xf slide.tar.gz
          cp slide/slide.pdf ./slide.pdf
      - env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create -d -n '' -t "$TAG_NAME" "$TAG_NAME" slide.tar.gz slide.pdf
